name: Feature Request
description: File a feature request.
title: "[Feature Request]: "
labels: ["feature request"]
assignees:
  - liangcha385
body:
  - type: markdown
    attributes:
      value: |
        This form is for requesting new features or improvements, and should not be used for bug reports or other issues.
        Make sure you have used the search tool to see if a similar request already exists. If we have previously closed a feature request, then please do not create another request.
  - type: textarea
    id: request_description
    attributes:
      label: Request Description
      description: Please provide a detailed explanation of your feature request, and if possible, please attach pictures or references
      value: "..."
